social_open_graph.settings:
  type: config_object
  label: 'Social Open Graph settings'
  mapping:
    settings:
      type: boolean
      label: 'Enable consent'
    cache_expiration:
      type: integer
      label: 'Cache expiration time'
    facebook_app_id:
      type: string
      label: 'Facebook App ID'
    facebook_app_secret:
      type: string
      label: 'Facebook App Secret'

