_core:
  default_config_hash: fc2lPUBS5PlJLPefA8I4U2ppCR0i-vCbmN1A8LGZtv8
rest_api_authentication_customer_admin_email: null
rest_api_authentication_license_key: null
rest_api_authentication_customer_id: ''
rest_api_authentication_customer_admin_token: ''
rest_api_authentication_customer_api_key: ''
rest_api_authentication_status: ''
enable_authentication: 1
authentication_method: 1
api_token: cOOHDlafx8Ek24hPS4rpe3DPJn3iw9PH6zEBsfj1sUn0ZQM2POdZSSNU7DHReGuc
rest_api_authentication_support_request_flag: APIAuthTab
application_name: GoPost
applications:
  d748afb7:
    name: GoPost
    auth_method: 'API Key'
    authentication_method: '1'
    header_info: 'Authorization: Basic {base64_encoded_credentials}'
    enable_authentication: 1
    rest_api_auth_type: '0'
    id: d748afb7
    is_default: false
rest_api_auth_type: '0'
